name: ts-tools
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
  - pypi
dependencies:
  - ipykernel=6.9
  - pandas=1.4
  - pebble=4.6
  - xtb=6.3
  - tqdm=4.64
  - pip=22.1
  - rdkit=2022.03
  - pytorch=1.12
  - xyz2mol=0.1
  - autode=1.4